name: testando-modulo-terraform
run-name: ${{ github.actor }} iniciou o teste do módulo terraform
on: [push]
jobs:
    tfsec:
        runs-on: ubuntu-lastest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install tfsec
              run: |
                curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
            - name: Run tfsec
              run: tfsec .
        